# Site settings
baseurl = "https://www.coredns.io"
languageCode = "en-us"
title = "CoreDNS"
theme = "landing-page-hugo"

[params]
	description = "DNS service discovery for the cloud, and (much) more!"

[[params.social]]
        title = "download"
        icon = "download"
	url = "https://github.com/miekg/coredns"
[[params.social]]
	title = "docs"
	icon = "book"
	url = "https://miek.nl/tags/coredns"
[[params.social]]
	title = "source"
	icon = "code"
	url = "https://github.com/miekg/coredns"
#[[params.social]]
#	title = "twitter"
#	icon = "twitter"
#	url = "https://twitter.com/corednsio"
