# Site settings
baseurl = "https://coredns.io"
languageCode = "en-us"
title = "CoreDNS"
theme = "landing-page-hugo"

[params]
	description = "DNS service discovery for the cloud, and (much) more!"

[[params.social]]
        title = "download"
        icon = "download"
	url = "https://github.com/coredns/coredns/releases"
[[params.social]]
	title = "blog"
	icon = "book"
	url = "https://blog.coredns.io"
[[params.social]]
	title = "source"
	icon = "code"
	url = "https://github.com/coredns/coredns"
