# Site settings
baseurl = "https://coredns.io"
languageCode = "en-us"
title = "CoreDNS"
theme = "landing-page-hugo"

[params]
	description = "Service discovery for the cloud, and (much) more!"

[[params.social]]
	title = "email"
	icon = "envelope-o"
	url = "mailto:coredns@miek.nl"
[[params.social]]
	title = "twitter"
	icon = "twitter"
	url = "https://twitter.com/corednsio"
[[params.social]]
	title = "github"
	icon = "github"
	url = "https://github.com/miekg/coredns"
